name: CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get short SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push Docker image (latest and SHA)
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/hello-app:latest
            ${{ secrets.DOCKER_USERNAME }}/hello-app:${{ env.SHORT_SHA }}

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Checkout manifests repo
        uses: actions/checkout@v4
        with:
          repository: dgporte/hello-manifests
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          path: manifests

      - name: Update manifests with new image tag
        run: |
          sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/hello-app:${{ env.SHORT_SHA }}|" manifests/deployment.yaml

      - name: Commit and push manifests
        run: |
          cd manifests
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add deployment.yaml
          git commit -m "Update image to ${{ env.SHORT_SHA }}"
          git push
